# Site settings
title: Coding With Tools
header-img: img/home-bg.png
email: jstooley823@gmail.com
copyright_name: jstooley
description: > # this means to ignore newlines until "baseurl:"
  Come code with me! 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: jstooley823
github_username:  jstooley
learn_profile: jstooley
email_username: jstooley823@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
